services:
    db:
        build: ./db
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        env_file: .env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - backend_network

    web:
        build: ./
        restart: unless-stopped 
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        env_file: .env
        depends_on:
            - db
        networks:
            - backend_network

volumes:
    db_data:

networks:
    backend_network:
        driver: bridge